services:
  - type: web
    name: domino-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
